baseURL = "https://fuckyoudynamicweb.com/" # Controls base URL
uglyurls = true
title = "Doc on the Rocks" # Homepage title and page title suffix
languageCode = "en-US" # Controls site language
paginate = 5 # Number of posts to show before paginating
theme = "hyde-x" # Set default theme
disqusShortname = "fuckyoudynamicweb" # Optional, add Disqus shortname for comments
enableRobotsTXT = true # Suggested, enable robots.txt file
MetaDataFormat = "toml"

[author]
    name = "Daniel Spisak"

[permalinks]
# Optional. Change the permalink format for the 'post' content type.
# The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
# Optional. Use if you want tags and lists.
   category = "categories"
   tag = "tags"

[params]
  truncate = true
  theme = "theme-base-09"
  highlight = "dark"
  tagline = "Smoke me a kipper, I'll be back for breakfast"
  home = "Blagh"

  # Used when a given page doesn't set its own.
  defaultDescription = "Blog entry"
  defaultKeywords = "blog,fnord"

  googleAnalytics = "UA-110594244-1" # Optional, add tracking Id for analytics
  gravatarHash = "99420eb3d52581434d66b08cf67f2e85"

  # Sidebar social links, these must be full URLs.
  github = "https://github.com/docwho76"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/dspisak"
  googleplus = ""
  facebook = "https://www.facebook.com/RickRollNeverGonnaGiveYouUpNeverGonnaLetYouDown666"
  twitter = "https://twitter.com/docwho76"
  youtube = ""
  email = ""

  # Other social-like sidebar links
  rss = true  # switch to true to enable RSS icon link
